
language:
  python
python:
 - "3.5"
install:
 - pip install -U pip
 - pip install -r requirements.txt
 - pip install coverage
 - pip install codecov
git:
  depth: 50
jobs:
  include:
  - name: "project-1"
    python: "3.8"
script:
  - coverage run -m pytest -q test/test_class.py
  - pytest --flake8
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6ba38871-5113-4f85-8d7a-56b97151d932
